name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update npm
        run: npm install npm@latest

      - name: Manually review vulnerabilities
        run: npm audit

      - name: Fix vulnerabilities automatically
        run: npm audit fix --force 

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy site to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
