name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Remove existing package-lock.json
        run: echo "Removing existing package-lock.json" && rm -f package-lock.json

      - name: Install dependencies
        run: echo "Installing dependencies" && npm ci --prefer-offline

      - name: Manually review vulnerabilities
        run: echo "Manually reviewing vulnerabilities" && npm audit

      - name: Fix vulnerabilities automatically
        run: echo "Fixing vulnerabilities automatically" && npm audit fix --force

      - name: Build
        run: echo "Building" && npm run build

      - name: Deploy site to gh-pages branch
        run: echo "Deploying site to gh-pages branch" && npx gh-pages -d build
