name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Remove existing package-lock.json
        run: rm -f package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Manually review vulnerabilities
        run: npm audit

      - name: Fix vulnerabilities automatically
        run: npm audit fix --force

      - name: Build
        run: npm run build

      - name: Deploy site to gh-pages branch
        run: npx gh-pages -d build
