name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --prefer-offline --no-audit

      - name: Build
        run: npm run build && mv build/* . && rm -rf build/

      - name: Deploy site to gh-pages branch
        run: npx gh-pages --dist . --branch gh-pages --add
